[package]
name = "draft_cube"
edition.workspace = true

[dependencies]
shader = { path = "./shader", package = "draft_cube_shader" }
trivalibs.workspace = true
png.workspace = true
bytemuck.workspace = true
