[package]
name = "draft_ball"
edition.workspace = true
version = "0.1.0"

[dependencies]
shader = { path = "./shader", package = "draft_ball_shader" }
trivalibs.workspace = true
png.workspace = true
bytemuck.workspace = true
